name: Blurt
markdown: redcarpet
highlighter: rouge
base_url: http://bitwiser.in/blurt
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "page:num"
#disqus: bitwiser
#ga_id: UA-47902363-1
ga_domain: bitwiser.in

description: blurt | A JS replacement for default alert() and confirm() and pronpt()
keywords: development, blog, coding, web development
twitter: brijeshb42
fb_page: bitwiser

links:
  facebook: brijeshb42
  twitter: brijeshb42
  email: brijeshb42@gmail.com
  github: brijeshb42/blurt

